
import OpenAI from "openai";
import { ProjectIdea, Difficulty, Domain } from "../types";

const getApiKey = () => {
  return import.meta.env.VITE_NVIDIA_API_KEY || '';
};

let client: OpenAI | null = null;

const getClient = () => {
  if (!client) {
    const apiKey = getApiKey();
    if (!apiKey) {
      throw new Error("API Key is missing. Please set VITE_NVIDIA_API_KEY in .env.local");
    }
    // Vite proxy handles the base URL rewrite
    client = new OpenAI({
      baseURL: `${window.location.origin}/api/nvidia`,
      apiKey: apiKey,
      dangerouslyAllowBrowser: true
    });
  }
  return client;
};

export async function generateNvidiaProject(level: Difficulty, domain: Domain): Promise<ProjectIdea> {
  const prompt = `
Generate a unique, innovative, and practical final year BCA project idea for a ${level} level student specializing in ${domain === 'all' ? 'Computer Science' : domain}.
The project should be based on current 2024-2025 industry trends.
Include a full implementation roadmap.
Make the tech stack appropriate for the ${level} level.

You MUST return a valid JSON object with the following structure:
{
  "title": "Project Title",
  "description": "Clear summary of the project goals",
  "techStack": ["Tech 1", "Tech 2"],
  "usp": "Unique Selling Point",
  "modules": ["Module 1", "Module 2", "Module 3"],
  "roadmap": [
    { "phase": "Phase Name", "tasks": ["Task 1", "Task 2"] }
  ]
}
Do not include any markdown formatting like \`\`\`json. Just return the raw JSON string.
`;

  try {
    const completion = await getClient().chat.completions.create({
      model: "meta/llama-3.1-405b-instruct",
      messages: [
        { role: "system", content: "You are a helpful assistant that generates project ideas in strict JSON format." },
        { role: "user", content: prompt }
      ],
      temperature: 0.6,
      top_p: 0.95,
      max_tokens: 4096,
    });

    const content = completion.choices[0]?.message?.content;
    console.log("NVIDIA RAW RESPONSE:", content);

    if (!content) {
      throw new Error("No content received from NVIDIA API");
    }

    // Attempt to clean markdown if present (e.g. ```json ... ```)
    const cleanedContent = content.replace(/```json\n?|\n?```/g, "").trim();

    try {
      const rawData = JSON.parse(cleanedContent);

      return {
        ...rawData,
        id: Math.random().toString(36).substring(7),
        level,
        domain,
        timestamp: Date.now(),
        // NVIDIA API doesn't provide grounding sources in the same way, so we leave it undefined or maybe add a generic source
        sources: [{ title: "Generated by Llama 3.1 Nemotron", uri: "https://build.nvidia.com/nvidia/llama-3.1-nemotron-70b-instruct" }]
      };
    } catch (parseError) {
      console.error("Failed to parse JSON from NVIDIA API:", cleanedContent);
      throw new Error("Failed to parse project data from AI response.");
    }
  } catch (error: any) {
    console.error("NVIDIA API Error:", error);
    throw error;
  }
}
