
import React from 'react';
import { ProjectIdea } from '../types.ts';
import { useToast } from '../context/ToastContext.tsx';

interface ProjectCardProps {
  project: ProjectIdea;
}

const ProjectCard: React.FC<ProjectCardProps> = ({ project }) => {
  const { addToast } = useToast();

  const copyToClipboard = () => {
    const text = `
Project Title: ${project.title}
Difficulty: ${project.level}
Domain: ${project.domain}

Description:
${project.description}

Tech Stack: ${project.techStack.join(', ')}

USP: ${project.usp}

Key Modules:
${project.modules.map(m => `- ${m}`).join('\n')}

Roadmap:
${project.roadmap.map(r => `${r.phase}:\n${r.tasks.map(t => `  - ${t}`).join('\n')}`).join('\n')}
    `.trim();
    
    navigator.clipboard.writeText(text);
    addToast('Project details copied to clipboard!', 'success');
  };

  const exportAsMarkdown = () => {
    const content = `# Project Idea: ${project.title}

## Overview
- **Difficulty:** ${project.level}
- **Domain:** ${project.domain}
- **USP:** ${project.usp}

## Description
${project.description}

## Tech Stack
${project.techStack.map(t => `- ${t}`).join('\n')}

## Modules
${project.modules.map(m => `- ${m}`).join('\n')}

## Implementation Roadmap
${project.roadmap.map(r => `### ${r.phase}\n${r.tasks.map(t => `- ${t}`).join('\n')}`).join('\n\n')}

---
Generated by BCA GenIdeas Pro
`;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.title.replace(/\s+/g, '_').toLowerCase()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-gray-100 animate-fade-in mb-12">
      <div className="p-8 bg-gradient-to-br from-slate-900 to-slate-800 text-white">
        <div className="flex flex-wrap justify-between items-start gap-4 mb-6">
          <div className="flex gap-2">
            <span className={`px-3 py-1 text-[10px] font-bold rounded-full uppercase tracking-widest border
              ${project.level === 'beginner' ? 'bg-green-500/10 border-green-500/30 text-green-400' : 
                project.level === 'intermediate' ? 'bg-blue-500/10 border-blue-500/30 text-blue-400' : 
                'bg-purple-500/10 border-purple-500/30 text-purple-400'}`}>
              {project.level}
            </span>
            <span className="px-3 py-1 text-[10px] font-bold rounded-full uppercase tracking-widest bg-white/10 border border-white/20 text-white/70">
              {project.domain}
            </span>
          </div>
          <div className="flex gap-2">
            <button
              onClick={copyToClipboard}
              className="p-2 bg-white/10 hover:bg-white/20 rounded-xl transition-all"
              title="Copy Text"
              aria-label="Copy project details to clipboard"
            >
              <i className="far fa-copy" aria-hidden="true"></i>
            </button>
            <button
              onClick={exportAsMarkdown}
              className="p-2 bg-white/10 hover:bg-white/20 rounded-xl transition-all"
              title="Export MD"
              aria-label="Export project details as Markdown"
            >
              <i className="fas fa-file-export" aria-hidden="true"></i>
            </button>
          </div>
        </div>
        <h3 className="text-3xl md:text-4xl font-extrabold leading-tight mb-4">{project.title}</h3>
        <p className="text-slate-300 text-lg max-w-3xl leading-relaxed">{project.description}</p>
      </div>

      <div className="p-8 space-y-12">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-6">
            <div className="bg-blue-50 p-6 rounded-3xl border border-blue-100">
              <h4 className="text-xs font-bold text-blue-600 uppercase tracking-widest mb-4 flex items-center gap-2">
                <i className="fas fa-layer-group"></i> Technologies
              </h4>
              <div className="flex flex-wrap gap-2">
                {project.techStack.map(tech => (
                  <span key={tech} className="bg-white px-3 py-1.5 rounded-xl text-sm font-semibold text-blue-800 shadow-sm border border-blue-100">
                    {tech}
                  </span>
                ))}
              </div>
            </div>

            <div className="bg-amber-50 p-6 rounded-3xl border border-amber-100">
              <h4 className="text-xs font-bold text-amber-600 uppercase tracking-widest mb-4 flex items-center gap-2">
                <i className="fas fa-sparkles"></i> Innovation (USP)
              </h4>
              <p className="text-amber-900 font-medium">{project.usp}</p>
            </div>
          </div>

          <div className="bg-gray-50 p-6 rounded-3xl border border-gray-100">
            <h4 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-4 flex items-center gap-2">
              <i className="fas fa-puzzle-piece"></i> Core Modules
            </h4>
            <div className="space-y-3">
              {project.modules.map((mod, idx) => (
                <div key={idx} className="flex items-center gap-3 text-gray-700 bg-white p-3 rounded-xl border border-gray-100 shadow-sm">
                  <span className="w-5 h-5 flex-shrink-0 bg-slate-100 text-slate-500 text-[10px] font-bold rounded flex items-center justify-center">0{idx + 1}</span>
                  <span className="text-sm font-medium">{mod}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div>
          <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-8 flex items-center gap-2 justify-center">
            <div className="h-[1px] w-8 bg-gray-200"></div>
            Implementation Roadmap
            <div className="h-[1px] w-8 bg-gray-200"></div>
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {project.roadmap.map((step, idx) => (
              <div key={idx} className="relative group">
                <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm group-hover:border-blue-300 transition-all h-full">
                  <div className="w-8 h-8 rounded-lg bg-slate-100 text-slate-500 flex items-center justify-center font-bold text-sm mb-4">
                    {idx + 1}
                  </div>
                  <h5 className="font-bold text-slate-900 mb-3 text-sm uppercase tracking-tight">{step.phase}</h5>
                  <ul className="space-y-2">
                    {step.tasks.map((task, tidx) => (
                      <li key={tidx} className="text-xs text-slate-500 flex gap-2">
                        <span className="text-blue-400">•</span>
                        {task}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>

        {project.sources && project.sources.length > 0 && (
          <div className="pt-8 border-t border-gray-100">
            <h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-4">Real-time Inspiration Sources</h4>
            <div className="flex flex-wrap gap-4">
              {project.sources.map((source, idx) => (
                <a 
                  key={idx} 
                  href={source.uri} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-xs text-blue-500 hover:text-blue-700 underline flex items-center gap-1"
                  aria-label={`${source.title} (opens in new tab)`}
                >
                  <i className="fas fa-link text-[8px]" aria-hidden="true"></i>
                  {source.title}
                </a>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ProjectCard;
